CoreTutorial/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreTutorial.Data;
using CoreTutorial.Services;
using CoreTutorial.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace CoreTutorial.Controllers
{
    public class AppController : Controller
    {
        private readonly INullMailService _mailService;
        private readonly IArtRepository _repository;

        public AppController(INullMailService mailService, IArtRepository repository)
        {
            _mailService = mailService;
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                _mailService.SendMessage("pujanisme@gmail.com", model.Subject, $"From: {model.Name} - {model.Email}, Message:{model.Message}");
                ViewBag.UserMessage = "Mail Sent";
                ModelState.Clear();
            }
            else
            {
            }
            return View();
        }

        public IActionResult About()
        {
            ViewBag.Title = "About Us";

            return View();
        }

        public IActionResult Shop()
        {
            //var results = _context.Products.
            //    OrderBy(p => p.Category).ToList();
            //return View();

            //var results = from p in _context.Products
            //              orderby p.Category
            //              select p;

            var results = _repository.GetAllProducts();
            return View(results);
        }
    }
}

CoreTutorial/Controllers/OrderItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CoreTutorial.Data;
using CoreTutorial.Data.Entities;
using CoreTutorial.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CoreTutorial.Controllers
{
    [Route("api/orders/{orderid}/items")]
    public class OrderItemsController : Controller
    {
        private readonly IArtRepository _repository;
        private readonly ILogger _logger;
        private readonly IMapper _mapper;

        public OrderItemsController(IArtRepository repository, ILogger<OrderItemsController> logger, IMapper mapper)
        {
            _repository = repository;
            _logger = logger;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Get(int orderId)
        {
            var order = _repository.GetOrderById(orderId);
            if (order != null)
            {
                return Ok(_mapper.Map<IEnumerable<OrderItem>, IEnumerable<OrderItemViewModel>>(order.Items));
            }

            return NotFound();
        }

        [HttpGet("{id}")]
        public IActionResult Get(int orderId, int id)
        {
            var order = _repository.GetOrderById(orderId);
            if (order != null)
            {
                var item = order.Items.Where(i => i.Id == id).FirstOrDefault();
                if (item != null)
                {
                    return Ok(_mapper.Map<OrderItem, OrderItemViewModel>(item));
                }
            }

            return NotFound();
        }
    }
}

CoreTutorial/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CoreTutorial.Data;
using CoreTutorial.Data.Entities;
using CoreTutorial.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CoreTutorial.Controllers
{
    [Route("api/[Controller]")]
    public class OrdersController : Controller
    {
        private readonly IArtRepository _repository;
        private readonly ILogger<OrdersController> _logger;
        private readonly IMapper _mapper;

        public OrdersController(IArtRepository repository, ILogger<OrdersController> logger, IMapper mapper)
        {
            _repository = repository;
            _logger = logger;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Get(bool includeItems = true)
        {
            try
            {
                var results = _repository.GetAllOrders(includeItems);
                return Ok(_mapper.Map<IEnumerable<Order>, IEnumerable<OrderViewModel>>(results));
            }
            catch (Exception ex)
            {
                _logger.LogError($"Failed to get Orders: {ex}");
                return BadRequest("Failed to get Orders");
            }
        }

        [HttpGet("{id:int}")]
        public IActionResult Get(int id)
        {
            try
            {
                var order = _repository.GetOrderById(id);
                if (order != null)
                    return Ok(_mapper.Map<Order, OrderViewModel>(order));
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Failed to get Orders: {ex}");
                return BadRequest("Failed to get Orders");
            }
        }

        [HttpPost]
        public IActionResult Post([FromBody]OrderViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var newOrder = _mapper.Map<OrderViewModel, Order>(model);
                    if (newOrder.OrderDate == DateTime.MinValue)
                    {
                        newOrder.OrderDate = DateTime.Now;
                    }
                    _repository.AddEntity(newOrder);
                    if (_repository.SaveAll())
                    {
                        return Created($"/api/orders/{newOrder.Id}", _mapper.Map<Order, OrderViewModel>(newOrder));
                    }
                }
                else
                {
                    return BadRequest(ModelState);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Failed to save Order: {ex}");
            }

            return BadRequest("Failed to save Order");
        }
    }
}

CoreTutorial/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreTutorial.Data;
using CoreTutorial.Data.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CoreTutorial.Controllers
{
    [Route("api/[Controller]")]
    public class ProductsController : Controller
    {
        private readonly IArtRepository _repository;
        private readonly ILogger<ProductsController> _logger;

        public ProductsController(IArtRepository repository, ILogger<ProductsController> logger)
        {
            _repository = repository;
            _logger = logger;
        }

        //[HttpGet]
        //public JsonResult Get()
        //{
        //    try
        //    {
        //        return Json(_repository.GetAllProducts());
        //    }
        //    catch (Exception ex)
        //    {
        //        _logger.LogError($"Failed to get products: {ex}");
        //        return Json("Bad Request");
        //    }
        //}

        [HttpGet]
        public IActionResult Get()
        {
            try
            {
                return Ok(_repository.GetAllProducts());
            }
            catch (Exception ex)
            {
                _logger.LogError($"Failed to get products: {ex}");
                return BadRequest("Failed to get products");
            }
        }
    }
}

CoreTutorial/Views/App/About.cshtml
<h2>About Us</h2>

CoreTutorial/Views/App/Contact.cshtml
@model ContactViewModel
@{
    ViewBag.Title = "Contact Us";
}
@section scripts
    {
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
}
<div class="col-md-6 col-md-offset-5">
    <div class="well">
        <form method="POST">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input type="text" asp-for="Name" value="" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email">Email</label>
                <input type="email" asp-for="Email" value="" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject">Subject</label>
                <input type="text" asp-for="Subject" value="" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Message">Message</label>
                <textarea rows="4" asp-for="Message" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary"><i class="fas fa-envelope"></i>Send Message</button>
                <div class="text-success">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

CoreTutorial/Views/App/Index.cshtml
@{
    ViewBag.Title = "HomePage";
}

<div class="row">
    <div class="col-md-6">
        <div class="product-info">
            <img src="~/img/Demon Mask.jpg" />

            <h3>Demon Mask</h3>
            <ul class="product-prop">
                <li>Price: Rs. 999</li>
                <li>Artist: Sabin Maharjan</li>
                <li>Description: Demon Mask</li>
            </ul>
            <button id="buyButton" class="btn btn-success">Buy!</button>
        </div>
    </div>
    <div class="col-md-6">
        <h1>This is a page for buying Nepali Products</h1>
    </div>
</div>
<div>
    <div id="loginToggle">Login</div>
    <form class="popupForm">
        <div>
            <label>UserName</label>
            <input type="text" value="" />
        </div>
        <div>
            <label>Password</label>
            <input type="password" value="" />
        </div>
        <div>
            <input type="checkbox" value="" />
            <label>Remember Me</label><br />
        </div>
        <div>
            <input type="submit" name="name" value="Login" />
        </div>
    </form>
</div>

CoreTutorial/Views/App/Shop.cshtml
@model IEnumerable<Product>

<h1>Shop</h1>
<p>Count: @Model.Count()</p>
<div class="row">
    @foreach (var p in Model)
    {

        <div class="col-md-3">
            <div class="well well-sm">

                <img src="~/img/@(p.ArtId).jpg" class="img-responsive" width="200px" height="200px" alt="@p.Title" />

                <h3>@p.Category - @p.Size</h3>
                <ul class="product-prop">
                    <li>Price: @p.Price</li>
                    <li>Artist: @p.Artist</li>
                    <li>Description: @p.ArtDescription</li>
                </ul>
                <button id="buyButton" class="btn btn-success">Buy!</button>
            </div>
        </div>

    }
</div>

CoreTutorial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Art Emporium: @ViewBag.Title </title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
    @*<div class="navbar navbar-light">
            <header class="container">
                <div class="navbar-brand">Welcome To Art Emporium</div>
                <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">&#9776;</button>
                <div id="menu" class="navbar navbar-collapse">
                     <ul class="nav navbar-nav">
                        <li><a asp-controller="App" asp-action="Index">Home</a></li>
                        <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
                        <li><a asp-controller="App" asp-action="About">About</a></li>
                    </ul>
                </div>
            </header>
        </div>*@

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <header class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#"><i class="fa fa-check"></i> Art Emporium</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li style="margin-right:15px;"><a asp-controller="App" asp-action="Index">Home</a></li>
                    <li style="margin-right:15px;"><a asp-controller="App" asp-action="Contact">Contact</a>
                    <li style="margin-right:15px;"><a asp-controller="App" asp-action="About">About</a></li>
                </ul>
            </div>
        </header>
    </nav>

    <section class="container">
        <h2 class="text-center"> @ViewBag.Title</h2>
        @RenderBody()
    </section>
    <footer class="container">
        <div class="text-center">
            Copyright 2017
        </div>
    </footer>

    <script src="~/jquery/dist/jquery.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/main.js"></script>
    @RenderSection("scripts", false)
</body>
</html>